spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update